import './globals.css'
import { Inter } from 'next/font/google'
import SideBar from '@/components/SideBar'
import { SessionProvider } from '@/components/SessionProvider'
// import { getSession } from 'next-auth/react'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Login from '@/components/Login'
import ClientProvider from '@/components/ClientProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)
  // console.log(session.user.image)
  return (
    <html lang="en">
     <body className="">
      <SessionProvider session={session}>
        {!session ? (
          <Login />
        ):(
          <div className='flex'>
          {/* sidebar */}
         <div className='bg-gray-700 max-w-xs h-screen  md:min-w-[15rem]'>
         <SideBar />
         </div>
          {/* client notifier */}
          
          <ClientProvider/>
  
          <div className='bg-[#141e30] flex-1'>
            {children}
          </div>
         </div>
        )}
  
       </SessionProvider>
     </body>
    </html>
  )
}
